version: '3.8'

services:
  backend:
    build: ./back
    container_name: pince_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./back/.env.production
    networks:
      - pince_net

networks:
  pince_net:
    driver: bridge
